2025-07-09 13:50:41,016 - frontend.views.settings_view - ERROR - Port update failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/settings/serial_port (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff90dc46010>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-07-09 13:50:41,017 - frontend.views.network_view - ERROR - Failed to fetch networks: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/networks (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff90db51350>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-07-09 13:50:41,017 - frontend.views.settings_view - ERROR - Settings fetch failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/settings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff90db53890>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-07-09 13:50:54,055 - frontend.views.settings_view - ERROR - Watchdog update failed: HTTP 404: {"detail":"Not Found"}
